name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 7.3.0
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^6.2.0
  photo_manager: ^2.1.0+1
  provider: ^6.0.2
  video_player: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NimbusBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold-Extended_32745.ttf
    - family: NimbusRegular
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Regular-Extended_32755.ttf
    - family: NimbusRegularItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Regular-Italic_32756.ttf
    - family: NimbusLight
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Light_32752.ttf
    - family: Nimbus
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT_32758.ttf
    - family: NimbusBlackBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Black-Extended_32740.ttf
    - family: NimbusItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold-Italic_32746.ttf
    - family: NimbusLightItalic
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Light-Italic_32751.ttf
    - family: NimbusSansBold
      fonts:
        - asset: fonts/Nimbus-Sans-D-OT-Bold_32747.ttf
